### ISSUE TITLE
Cadran rotatif fils bleu et bleu/blanc

### ISSUE THREAD

**Issue by Tekkharibo** [revolunet/s63#1]
Bonjour,

Dans votre readme, vous notez que vous ne savez pas à quoi servent les fils bleu et bleu/blanc du cadran. Ils sont la pour informer de l'activité du cadran, dès qu'on le tourne il laisse passer le courant et dès qu'il est de retour en position normal il se ferme.

Merci beaucoup pour ce Readme qui est très clair et permet de facilement monter un projet avec un Socotel S63

Bonne journée

**Comment by revolunet** [comment]
Merci beaucoup pour la précision 🙏  je mets à jour le README :)
